# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .test_moe_align_block_size import test_accuracy_moe_align_block_size
from .test_selective_scan_fwd import test_accuracy_selective_scan_fwd
from .test_paged_attention_v1 import test_accuracy_paged_attention_v1
from .test_scaled_fp8_quant import test_accuracy_scaled_fp8_quant
from .test_rotary_embedding import test_accuracy_rotary_embedding
from .test_fused_add_rms_norm import test_accuracy_fused_add_rms_norm
from .test_topk_softmax import test_accuracy_topk_softmax
from .test_fused_qk_norm_rope import test_accuracy_fused_qk_norm_rope
from .test_scaled_int8_quant import test_accuracy_scaled_int8_quant
from .test_cutlass_scaled_mm import test_accuracy_cutlass_scaled_mm
from .test_rms_norm import test_accuracy_rms_norm
from .test_rms_norm_dynamic_per_token_quant import test_accuracy_rms_norm_dynamic_per_token_quant
from .test_moe_sum import test_accuracy_moe_sum
from .test_permute_cols import test_accuracy_permute_cols
from .test_shuffle_rows import test_accuracy_shuffle_rows
from .test_convert_fp8 import test_accuracy_convert_fp8
from .test_hadacore_transform import test_accuracy_hadacore_transform
from .test_swap_blocks import test_accuracy_swap_blocks
from .test_grouped_topk import test_accuracy_grouped_topk
from .test_rms_norm_per_block_quant import test_accuracy_rms_norm_per_block_quant
from .test_gptq_shuffle import test_accuracy_gptq_shuffle
from .test_merge_attn_states import test_accuracy_merge_attn_states
from .test_reshape_and_cache import test_accuracy_reshape_and_cache
from .test_reshape_and_cache_flash import test_accuracy_reshape_and_cache_flash
from .test_concat_and_cache_mla import test_accuracy_concat_and_cache_mla
from .test_paged_attention_v2 import test_accuracy_paged_attention_v2
from .test_gptq_gemm import test_accuracy_gptq_gemm
from .test_cutlass_pack_scale_fp8 import test_accuracy_cutlass_pack_scale_fp8
from .test_cutlass_scaled_mm_azp import test_accuracy_cutlass_scaled_mm_azp
from .test_gptq_marlin_24_gemm import test_gptq_marlin_24_gemm as test_accuracy_gptq_marlin_24_gemm
from .test_copy_blocks import test_accuracy_copy_blocks
from .test_copy_blocks_mla import test_accuracy_copy_blocks_mla
from .test_allspark_w8a16_gemm import test_accuracy_allspark_w8a16_gemm
from .test_gather_and_maybe_dequant_cache import test_accuracy_gather_and_maybe_dequant_cache
from .test_convert_vertical_slash_indexes import test_accuracy_convert_vertical_slash_indexes
from .test_cp_gather_cache import test_accuracy_cp_gather_cache
from .test_cp_gather_indexer_k_quant_cache import test_accuracy_cp_gather_indexer_k_quant_cache
from .test_marlin_int4_fp8_preprocess import test_marlin_int4_fp8_preprocess as test_accuracy_marlin_int4_fp8_preprocess
from .test_gptq_marlin_gemm import test_gptq_marlin_gemm as test_accuracy_gptq_marlin_gemm
from .test_ggml_mul_mat_a8 import test_accuracy_ggml_mul_mat_a8
from .test_ggml_mul_mat_vec_a8 import test_accuracy_ggml_mul_mat_vec_a8
from .test_gptq_marlin_moe_repack import test_accuracy_gptq_marlin_moe_repack
from .test_awq_marlin_moe_repack import test_accuracy_awq_marlin_moe_repack
from .test_moe_lora_align_block_size import test_accuracy_moe_lora_align_block_size
from .test_batched_moe_align_block_size import test_batched_moe_align_block_size as test_accuracy_batched_moe_align_block_size
from .test_apply_repetition_penalties_cuda import test_accuracy_apply_repetition_penalties_cuda
from .test_awq_gemm import test_accuracy_awq_gemm
from .test_ggml_dequantize import test_accuracy_ggml_dequantize
from .test_ggml_moe_a8 import test_accuracy_ggml_moe_a8
from .test_ggml_moe_a8_vec import test_accuracy_ggml_moe_a8_vec
